### ISSUE TITLE
Avoid moonshot-dbus-launch

### ISSUE THREAD

**Issue by jennifer-richards** [painless-security/moonshot-ui#16]
In debian bug #836116, I received the following comments about our moonshot-dbus-launch script.
As described in <https://lists.debian.org/debian-devel/2016/08/msg00554.html>
I'm trying to reduce how much dbus-launch is used in Debian.
moonshot-ui currently runs dbus-launch via moonshot-dbus-launch
if DBUS_SESSION_BUS_ADDRESS is unset.

One issue with this approach is that it second-guesses how the D-Bus
client implementation itself will find the session bus. In recent libdbus
and GDBus, the fallback behaviour if DBUS_SESSION_BUS_ADDRESS is unset
is to look for $XDG_RUNTIME_DIR/bus: if the environment variable is
set, that directory contains ./bus, and ./bus is a socket owned by
the current uid, then libdbus and GDBus will automatically use it. In
particular, the dbus-user-session Debian package sets up this situation.
moonshot-dbus-launch should not run dbus-launch without first looking
for that socket.

Another issue with the approach moonshot-ui has taken is that it relies
on dbus-launch, which is X11-specific legacy code that does several
things, none of them particularly well.
This Flatpak commit illustrates how eval `dbus-launch` can be replaced
by invoking dbus-daemon directly, avoiding the X11-specific dbus-launch:
<https://github.com/flatpak/flatpak/commit/6cc8062cfb3f9410d54a27e7ccca77c103e441e8>.
It is possible to send both the address and the pid to stdout
("--print-address=1 --print-pid=1") if that would be easier to deal
with; their order is undocumented but predictable, and I don't intend
to break it in future D-Bus releases.

Alternatively, and perhaps most simply, moonshot-ui could stop trying to
compensate for a missing session bus address at all. On systems with
$XDG_RUNTIME_DIR/bus, it would "just work" anyway; or when run under X11
(even with no dbus-daemon running), X11 autolaunching would create a
dbus-daemon anyway; or if moonshot-ui is being run in a non-GUI
environment (can that even make sense?), its documentation could mention
that this requires using

    dbus-run-session -- COMMAND [ARGS...]

which has been available since dbus 1.8, and automatically cleans up
the dbus-daemon after COMMAND terminates (successfully or not).

This is really an upstream bug. If you forward it upstream, please
quote the full text of this bug report and let upstream make their
own decisions.

Thanks,
    S

Launchpad Details: [#LP1618562](https://bugs.launchpad.net/bugs/1618562) Sam Hartman - 2016-08-30 17:20:17 +0000

**Comment by jennifer-richards** [comment]
As I told Simon, I'm not sure that we actually fail to respect XDF_RUNTIME_DIR/bus because of the way the dbus_connect function works in libmoonshot/libmoonshot-dbus.c.  However, I do think that launching the daemon directly might make a lot more sense than using the shell script we have.

Launchpad Details: [#LPC](https://bugs.launchpad.net/moonshot-ui/+bug/1618562/comments/1) Sam Hartman - 2016-08-30 17:23:12 +0000

**Comment by jennifer-richards** [comment]
Direct link to the Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836116

**Comment by jennifer-richards** [comment]
# Test

Note regarding testing: You will need either a moonshot-enabled program (such as Moonshot's ssh, gss-client, or tidc) or the `examples/client` program from the moonshot-ui build tree.

## Steps
1. Install the moonshot-ui and libmoonshot packages. Launch `moonshot` and ensure that none of the credentials are assigned to any services (Select a credential, click edit, then select each entry in the 'services' box and click remove. Click 'ok' and repeat for each credential.)
2. Open two shell windows
3. In one window, run `ps ax | grep dbus-daemon` and note how many processes are listed
4. In the other window, set and export the environment variable `DBUS_SESSION_BUS_ADDRESS` to an invalid bus name (e.g., in bash: `export DBUS_SESSION_BUS_ADDRESS=invalid` or some other random string). Be sure that `DISPLAY` is set (usually to `:0` or `:0.0`)
5. Run a program that uses `libmoonshot` to choose a credential (see note)
6. Before selecting a credential, in the first shell window, run `ps ax | grep dbus-daemon` again
7. Select an identity and close the moonshot window if it does not close on its own
8. Once again, run `ps ax | grep dbus-daemon` in the first shell window

## Expected results
1. In step 5, a moonshot window should appear. The shell window will likely have a message like
```
Activating service name='org.janet.Moonshot'
Successfully activated service 'org.janet.Moonshot'
```
2. In step 6, there should be one more `dbus-daemon` process than before. It should look like:
```
10976 pts/0    S+     0:00 /usr/bin/dbus-daemon --nofork --print-address --nopidfile --config-file /usr/share/moonshot-ui/dbus/org.janet.Moonshot.conf
```
3. In step 7, the program that requested an identity should have received the identity you selected and should react appropriately
4. In step 8, the new process listed in step 6 should be gone, and only the processes from step 3 should be present

## Additional test
Repeat the above, but in step for, `su` to root (using only `su` - do not use `su -`) instead of setting an invalid `DBUS_SESSION_BUS_ADDRESS`. The behavior should be the same.

**Comment by sebastianr6** [comment]
Tests and Additional Tests run as expected using tidc
