### ISSUE TITLE
Password prompt after using a credential that was imported with password

### ISSUE THREAD

**Issue by jennifer-richards** [painless-security/moonshot-ui#18]
I import a credential using the Moonshot webp XML file. As part of this, a password is defined, as well as a service rule. The first time I try to access the service, I am prompted to enter the password for the identity I imported. This is wrong. 

Since the password is defined and imported, this should also be retrieved and passed along without *any* interaction.

Launchpad Details: [#LP1750574](https://bugs.launchpad.net/bugs/1750574) Stefan Paetow - 2018-02-20 13:28:27 +0000

**Comment by jennifer-richards** [comment]
The problem seems to be that whereas MoonshotServer.install_id_card (used by moonshot-webp) sets the idcard.store_password = true, the import_identities_cb does not.

I've created a trivial patch in my GH page (https://github.com/alejandro-perez/moonshot-ui/compare/fix_import) that updates the Parser class to return IdCard with the store_password set whenever needed. It works in my tests, but please, review and apply.

Launchpad Details: [#LPC](https://bugs.launchpad.net/moonshot-ui/+bug/1750574/comments/1) Alejandro Perez - 2018-02-20 13:48:34 +0000

**Comment by jennifer-richards** [comment]
I've pulled Alejandro's patch in to the next release.

**Comment by jennifer-richards** [comment]
# Test

## Steps
1. Create a credential XML file that includes a password
2. Import the credential using `moonshot-webp`
3. Start the moonshot ui (with `moonshot`)
4. Open the credential you just imported
5. Connect to a service using this credential (with SSH or gss-client)

## Expected results
1. The import should succeed
2. When examined, the credential should have a password set and the "Remember password" box should be ticked
3. There should be no prompt for the password when using the credential

## Additional test
Remove the credential from the moonshot identity selector UI. Edit the XML file to remove the password field. Repeat the test. 

The credential should still import, but should *not* have a password in the UI and the "Remember password" box should be unticked. You should be prompted for a password when using the credential.

**Comment by sebastianr6** [comment]
Tests perform as expected. "Remember password" checkbox in the UI does not get ticked unless selected during the prompt in the additional test.
