### ISSUE TITLE
Identity selector fails with "Couldn't own name" error when running in a "su" shell

### ISSUE THREAD

**Issue by jennifer-richards** [painless-security/moonshot-ui#19]
When running as root after `su`, the following error occurs trying to run the identity selector:

```
$ su
Password: 
root@sshd:/home/jennifer# moonshot
Error while attempting to load from /root/.local/share/moonshot-ui/identities.txt: No such file or directory

** (moonshot:31118): ERROR **: moonshot-identity-manager-app.vala:399: Couldn't own name 'org.janet.Moonshot' on dbus or show previously launched identity manager.
Trace/breakpoint trap
```

If `su -` is used, the error about the missing `identities.txt` file is reported but the UI starts.

This affects at least Debian jessie versions 1.0.3-1 to 1.0.6-2

This is probably related to #10, but that particular failure mode has been eliminated as of 29fe8cd1eff5964712c87d001587412c0d1a5e03.

**Comment by jennifer-richards** [comment]
This occurs because `su` (without the `-` option) preserves the environment of the user who called it. This includes a `DBUS_SESSION_BUS_ADDRESS` variable that is set to the address of the original user's session bus. When this is set, DBus implementations use its value as the address of the session bus. In most systems, even root cannot connect to another user's session bus, so moonshot fails to connect to the bus.

If `DBUS_SESSION_BUS_ADDRESS` is unset, most DBus implementations will attempt to start their own session bus on the current display. This is why `su -` works - the root user starts up its own session bus.

Whether or not to start up a session bus is really a question for the distribution / system admin, not for an individual program. While we could catch this situation and unset the environment variable, that is really not our business.

It is a user error to try to run `moonshot` with an invalid `DBUS_SESSION_BUS_ADDRESS`. I think the best thing to do is to emit a meaningful error message and let the user fix their script / system in whatever way is appropriate for their situation.

**Comment by jennifer-richards** [comment]
# Test

## Steps
1. Install the identity selector
2. Switch to root with `su` for the rest of the steps (if you're already root, switch to another user instead)
3. Run `moonshot`
4. Run `dbus-run-session moonshot`
5. Unset the `DBUS_SESSION_BUS_ADDRESS` (in bash, this is `unset DBUS_SESSION_BUS_ADDRESS`)
6. Run `moonshot`

## Expected results
1. In step 3, you should receive a message about failure to connect to the session bus. This should include a hint to try the ways of fixing this that we're about to test
2. In steps 4 and 6, the moonshot identity selector UI should appear

## Additional tests
Repeat this using `su -`. The identity selector should appear in all cases (though as long as steps 4 and 6 behave as described, the same error message on step 3 is also acceptable).

As your original user (before calling `su` in any form), run
```
DBUS_SESSION_BUS_ADDRESS=something_invalid moonshot
```
You should get the error message.

Edit: The instructions for the "Additional tests" originally specified the wrong env variable to set. Fixed.

**Comment by sebastianr6** [comment]
Expected and additional tests result as expected, with the exception of running 'DBUS_SESSION_BUS=something_invalid moonshot'. This still opens the identity selector, but without any of the available identities inside.

**Comment by jennifer-richards** [comment]
Oops - those instructions were incorrect. It should have been `DBUS_SESSION_BUS_ADDRESS=something_invalid`. Can you try again?

**Comment by sebastianr6** [comment]
Running just DBUS_SESSION_BUS_ADDRESS=something_invalid as a regular user throws no errors @jennifer-richards

**Comment by jennifer-richards** [comment]
Did you include the "moonshot" afterwards? The full command should be:
```
DBUS_SESSION_BUS_ADDRESS=something_invalid moonshot
```

**Comment by sebastianr6** [comment]
Whoops, now the error is thrown as expected.
