### ISSUE TITLE
Replace dbus-glib with gdbus

### ISSUE THREAD

**Issue by jennifer-richards** [painless-security/moonshot-ui#20]
To resolve this issue, all traces of dbus-glib should be removed from the project. This only affects libmoonshot1 - anything built with Vala should already be using gdbus.

The server side of the identity selector is implemented through Vala code. Vala has supported gdbus since 0.9.2 and dbus-glib was deprecated in 0.9.8. After 0.12.1, dbus-glib has been removed entirely. This applies to all Debian versions since (and including) wheezy and to CentOS 7. CentOS 6 uses Vala 0.10.4-1 (via EPEL), which can build either with dbus-glib or gdbus.

The libmoonshot1 client uses dbus-glib for compatibility with older systems (Debian wheezy?). This needs to be replaced.

**Comment by jennifer-richards** [comment]
# Test
To be sure we know what versions are running, these tests *must* be run on a machine moonshot-ui and libmoonshot installed from packages.

I'm not absolutely sure these provide full test coverage - feel free to modify the tests to do a more thorough job.

## Steps
1. Use `moonshot-webp` to install a credential
2. Make a moonshot-authenticated connection (e..g, using moonshot-enabled ssh or making a TID request with tidc)

## Expected results
1. The `moonshot-webp` command should successfully import a credential
2. The moonshot identity selector UI should appear and a connection using the selected credential should succeed

**Comment by sebastianr6** [comment]
Results were as expected, tidc connection was successful
