### ISSUE TITLE
GSS Client fails during authorization process

### ISSUE THREAD

**Issue by sebastianr6** [painless-security/moonshot-ui#25]
![capture](https://user-images.githubusercontent.com/39917577/41369838-06f74ac2-6f14-11e8-9a29-adf2a6405cc8.PNG)

**Comment by jennifer-richards** [comment]
This was with 1.1.0~1 on CentOS 7. With 1.0.5-2, the connection fails with invalid credentials but without the GLib-CRITICAL warnings.

**Comment by jennifer-richards** [comment]
Same behavior on Debian jessie:
```
$ gss-client -mech {1.3.6.1.5.5.15.1.1.18} localhost user@host Frogs

(process:6434): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed

(process:6434): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed
Sending init_sec_context token (size=32)...continue needed...
Sending init_sec_context token (size=29)...continue needed...
GSS-API error initializing context: Unspecified GSS failure.  Minor code may provide more information
GSS-API error initializing context: Generic RADIUS failure
```

```
$ sudo gss-server -verbose user@host
starting...
Received token (size=32): 
60 1e 06 09 2b 06 01 05 05 0f 01 01 12 06 01 00 
00 00 02 00 00 00 09 75 73 65 72 2f 68 6f 73 74 

Sending accept_sec_context token (size=45):
60 2b 06 09 2b 06 01 05 05 0f 01 01 12 06 02 00 
00 00 03 00 00 00 09 75 73 65 72 2f 68 6f 73 74 
80 00 00 05 00 00 00 05 01 00 00 05 01 
continue needed...
Received token (size=29): 
60 1b 06 09 2b 06 01 05 05 0f 01 01 12 06 01 80 
00 00 04 00 00 00 06 02 00 00 06 01 40 
Sending accept_sec_context token (size=31):
60 1d 06 09 2b 06 01 05 05 0f 01 01 12 06 02 80 
00 00 01 00 00 00 08 00 0d 00 00 00 00 00 10 
GSS-API error accepting context: Unspecified GSS failure.  Minor code may provide more information
GSS-API error accepting context: Unknown code rse 17
```

**Comment by jennifer-richards** [comment]
This was happening because the `moonshot_get_identity()` was being called with null nai and password parameters. These are required to be non-null by the moonshot dbus server. The old dbus-glib library implicitly converted nulls to empty strings, but the gdbus library does not do this.

This is fixed by 51f2bfd279d9878dba0a7995b516ad605c4a9cf6, which explicitly converts nulls to empty strings for the dbus method call.

This should be fixed in 1.1.0~2, so please try again with that.

**Comment by jennifer-richards** [comment]
# Test

## Steps
1. Install the updated moonshot-ui packages
2. Make a gss-client to gss-server connection with Moonshot using an identity you have not used before. Choose an identity and be sure the "remember this choice" button is checked before sending
3. Repeat

## Expected results
1. The identity selector should pop up on your first gss-client authentication
2. The identity selector should not pop up on your second
3. There should be no GLib-CRITICAL warnings

Note: it does not matter whether the authentication succeeds or not - as long as an identity is selected, this test passes. I.e., an "invalid credential" outcome of the GSS authentication is ok.

**Comment by sebastianr6** [comment]
Tests result as expected on newest package
