### ISSUE TITLE
Get rid of shibboleth packaging

### ISSUE THREAD

**Issue by alejandro-perez** [painless-security/moonshot-ui#28]
NOTE: This does not belong to Moonshot-ui, but I failed to find mech_eap in your list of repositories. Please, place it where you think it belongs.

Currently we are shipping our own version of the Shibboleth software. However, the software is already available in Debian and Ubuntu (official repositories) and Centos 6 and 7 (through the Shibboleth official repository). 

One year ago I did a thorough review and realised that the versions in the Moonshot repository were just a freeze of the Shibboleth repositories. In particular HEAD is in:
* opensaml: 3d299ff (Scott) == tag 2.5.5 + 2. No custom changes here.
* resolver: 13e21ba (Jennifer) == tag 1.0.0 + 1. The change Jennifer introduced in this commit are already included upstream (I requested Scott to include them).
* sp: 86fd94f (Jennifer) == old_upstream + 1. Rename from shibboleth to shibboleth-sp, source of our problems :).
* xmltooling: 69bf5fe (Rod) == old_upstream. No custom changes here.

As part of the CI environment we are building, I have built mech_eap for Centos 6/7, Debian 8/9 and Ubuntu 14/16/18 using distribution-based shibboleth versions without major problems.

I understand that probably shipping our versions was required to introduce/backport changes that were required by moonshot (basically, GSS attributes support I guess), but that are now included in upstream.

Hence, I think packages should be built using those official ones

**Comment by jennifer-richards** [comment]
This sounds like a great plan to me. A few weeks back I built a CentOS 7 mech_eap package using the official Shibboleth packages without any trouble here, either.

I will see about getting this taken care of. We do have a GitHub repo for mech_eap, but it's currently old and private. I'm not sure what its purpose is, but I'll look into it.

**Comment by alejandro-perez** [comment]
Let me know if you need anything, but for what I can remember, it was as easy as just:
```
BuildRequires:	 %{_moonshot_krb5} >= 1.9.1
BuildRequires:	 moonshot-ui-devel
BuildRequires: jansson-devel
Requires:	moonshot-ui
BuildRequires: libradsec-devel >= 0.0.3
BuildRequires: shibboleth-devel >= 2.5
BuildRequires: libshibresolver-devel
```
The rest of the spec file remains as it was.

**Comment by jennifer-richards** [comment]
Thanks :)

**Comment by spaetow** [comment]
I would also recommend that we get the old packages marked as obsoleted, i.e. that we don't have dramas when you upgrade from our old packages to the new packages with the new upstream packages.

**Comment by alejandro-perez** [comment]
Closed as in our Build System this has already happen
